/**
 * 
 */
package org.tedros.it.tools.domain;

/**
 * @author Davis Gordon
 *
 */
public interface DomainApp {

	static final String SEPARATOR = "_";
	static final String VIEW = "VIEW";
	static final String MODULE = "MODULE";
	static final String FORM = "FORM";
	
	static final String EVIDENCE_MANAGER = "EVIDENCE_MANAGER";
	static final String EVIDENCE_CAPTURE = "EVIDENCE_CAPTURE";
	static final String EVIDENCE_REPORT = "EVIDENCE_REPORT";
	static final String REDMINE_TOOLS = "REDMINE_TOOLS";
	static final String CHANGE_MANAGER = "CHANGE_MANAGER";
	static final String CHANGE_MANAGER_DASHBOARD = "CHANGE_MANAGER_DASHBOARD";
	static final String CHANGE_MANAGER_GMUD_EDIT = "CHANGE_MANAGER_GMUD_EDIT";
	static final String CHANGE_MANAGER_GMUD_APPROVE = "CHANGE_MANAGER_GMUD_APPROVE";
	static final String SEP = SEPARATOR;
	
	static final String MNEMONIC = "ISPT";
	
	static final String CHANGE_MANAGER_MODULE_ID = MNEMONIC + SEP + CHANGE_MANAGER + SEP + MODULE;
	static final String CHANGE_MANAGER_DASHBOARD_VIEW_ID = MNEMONIC + SEP + CHANGE_MANAGER_DASHBOARD + SEP + VIEW;
	static final String CHANGE_MANAGER_DASHBOARD_FORM_ID = MNEMONIC + SEP + CHANGE_MANAGER_DASHBOARD + SEP + FORM;
	
	static final String CHANGE_MANAGER_GMUD_EDIT_VIEW_ID = MNEMONIC + SEP + CHANGE_MANAGER_GMUD_EDIT + SEP + VIEW;
	static final String CHANGE_MANAGER_GMUD_EDIT_FORM_ID = MNEMONIC + SEP + CHANGE_MANAGER_GMUD_EDIT + SEP + FORM;
	
	static final String CHANGE_MANAGER_GMUD_APPROVE_VIEW_ID = MNEMONIC + SEP + CHANGE_MANAGER_GMUD_APPROVE + SEP + VIEW;
	static final String CHANGE_MANAGER_GMUD_APPROVE_FORM_ID = MNEMONIC + SEP + CHANGE_MANAGER_GMUD_APPROVE + SEP + FORM;

	static final String EVIDENCE_MANAGER_MODULE_ID = MNEMONIC + SEP + EVIDENCE_MANAGER + SEP + MODULE;
	static final String EVIDENCE_MANAGER_FORM_ID = MNEMONIC + SEP + EVIDENCE_MANAGER + SEP + FORM;
	static final String EVIDENCE_MANAGER_VIEW_ID = MNEMONIC + SEP + EVIDENCE_MANAGER + SEP + VIEW;
		
	static final String EVIDENCE_REPORT_FORM_ID = MNEMONIC + SEP + EVIDENCE_REPORT + SEP + FORM;
	static final String EVIDENCE_REPORT_VIEW_ID = MNEMONIC + SEP + EVIDENCE_REPORT + SEP + VIEW;
	
	static final String EVIDENCE_CAPTURE_FORM_ID = MNEMONIC + SEP + EVIDENCE_CAPTURE + SEP + FORM;
	static final String EVIDENCE_CAPTURE_VIEW_ID = MNEMONIC + SEP + EVIDENCE_CAPTURE + SEP + VIEW;
	
	static final String REDMINE_TOOLS_MODULE_ID = MNEMONIC + SEP + REDMINE_TOOLS + SEP + MODULE;
	static final String REDMINE_TOOLS_FORM_ID = MNEMONIC + SEP + REDMINE_TOOLS + SEP + FORM;

}
