package org.tedros.redminetools.module.ai.function;

import org.slf4j.Logger;
import org.tedros.ai.TFunctionHelper;
import org.tedros.ai.function.TFunction;
import org.tedros.ai.function.model.Response;
import org.tedros.ai.function.model.ViewPath;
import org.tedros.api.form.ITFieldBox;
import org.tedros.api.form.ITModelForm;
import org.tedros.api.presenter.view.ITView;
import org.tedros.core.context.TViewDescriptor;
import org.tedros.core.context.TedrosAppManager;
import org.tedros.fx.presenter.dynamic.TDynaPresenter;
import org.tedros.fx.presenter.model.behavior.TViewBehavior;
import org.tedros.redminetools.module.tools.model.TerosRedmineMV;
import org.tedros.redminetools.module.tools.model.TerosRedmineModel;
import org.tedros.util.TLoggerUtil;

import javafx.application.Platform;
import javafx.scene.web.WebView;

public class ShowHtmlAiResponse extends TFunction<HtmlContent> {
	
	private static final Logger LOGGER = TLoggerUtil.getLogger(ShowHtmlAiResponse.class);
	
	private static final String PROMPT = """
    This function is responsible for displaying HTML content generated by the AI in the system interface.

    Purpose:
    - Render dynamic HTML fragments created by the AI, providing users with visually organized and interactive responses.

    Usage Context:
    - The function should be called whenever the AI generates HTML content intended for user display.
    - The target view ('Teros AI Response') must be open before invoking this function.

    Behavior:
    - Accepts only valid HTML fragments suitable for direct insertion into a <div> container.
    - Ensures the content is safe, readable, and visually appealing within the application interface.

    Important Rules:
    - The view named 'Teros AI Response' must be opened before showing any HTML content.
    - To open the view:
        1. Use the 'list_all_view_path' function to locate the correct view path.
        2. Then open it using the 'call_view' function.

    Instructions for the AI:
    - Generate only valid HTML fragments that can be inserted directly into a <div> container.
    - Do NOT include <html>, <head>, <body>, or <script> tags except for <div class="mermaid"> blocks to render diagrams.
    - You may use the Mermaid library (already loaded in the page) to generate diagrams and charts. To do this, create a <div class="mermaid"> element containing the Mermaid syntax for the desired diagram.
    - Supported diagram types include flowcharts, sequence diagrams, class diagrams, state diagrams, entity relationship diagrams, user journey diagrams, Gantt charts, pie charts, and more as per Mermaid documentation.
    - Use only standard HTML elements and inline CSS styles.
    - The output must be a pure HTML snippet, safe and compatible with direct rendering inside the view.
    - Do not include code fences or Markdown formatting — return plain HTML only.
    - Ensure the content is visually organized and clearly readable when rendered in the 'Teros AI Response' view.
    - After generating the HTML, call the function 'show_html_content' passing the HTML in the attribute 'htmlContent'.
    Example for a Mermaid diagram:
    show_html_content(htmlContent="<div class='mermaid'>graph TD; A-->B; B-->C; C-->A;</div>")
    """;
	
	public ShowHtmlAiResponse() {
		super("show_html_content", PROMPT, HtmlContent.class, 
				v->{
					LOGGER.info("Conteudo HTML recebido: {}",v.htmlContent());
					return run(v); 
				});
	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	private static Response run(HtmlContent v) {
		TedrosAppManager manager = TedrosAppManager.getInstance();
		
		ITView<TDynaPresenter> vw = manager.getCurrentView();
		
		if(vw==null || vw.gettPresenter().getModelViewClass()!=TerosRedmineMV.class) {
			
			TViewDescriptor vd = manager.getViewDescriptor(TerosRedmineMV.class, TerosRedmineModel.class);
			
			ViewPath path = new ViewPath();
			path.setViewPath(vd.getPath());
			
			LOGGER.info("Tentando abrir a view: {}", path.getViewPath());
			
			manager.listenView(c-> run(v), path.getViewPath());
			
			TFunctionHelper.callUpViewFunction().getCallback().apply(path);
			
			return new Response("Successful");
		} else {
		
			TDynaPresenter p = vw.gettPresenter();
			 
			Platform.runLater(()->{						
				
				ITModelForm form = ((TViewBehavior) p.getBehavior()).getForm();
				
				WebViewBridge webViewBridge = form.gettObjectRepository().get("webviewbridge");
				
				if(webViewBridge==null) {							
					ITFieldBox fdbox = form.gettFieldBox("webContent");
					WebView wv = (WebView) fdbox.gettControl();
					webViewBridge = new WebViewBridge(wv);
					form.gettObjectRepository().add("webviewbridge", webViewBridge);
				}
				
				webViewBridge.run(v.htmlContent());
				
			});
			
			return new Response("Successful");
		}
	}	

}